### ISSUE TITLE
[Idea] Add pattern configuration for links detection

### ISSUE THREAD

**Issue by vincentchalamon** [php-documentation-generator/php-documentation-generator#27]
For classes such as Symfony (starting with `Symfony\\*`), it could be interesting to create a link to its doc (https://symfony.com/doc/current/index.html).

We could imagine a configuration such as:
```yaml
pdg:
    references:
        links_patterns:
            'Symfony\\': 'https://symfony.com/doc/current/index.html'
            'ApiPlatform\\': 'https://api-platform.com/docs/'
```
